---
env:
  REPO_NAME: gatblau
  IMG_NAME: art-buildah

functions:
  - name: build-image
    description: build the docker image from an existing context
    run:
      - docker build --build-arg APP_NAME=art-linux-${ARTISAN_REF} -t ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF} .
      - docker tag ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF} ${REPO_NAME}/${IMG_NAME}:latest

  - name: push-image
    description: push the created docker image to the container registry
    run:
      - docker push ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF}
      - docker push ${REPO_NAME}/${IMG_NAME}:latest

  - name: release-image
    description: build the ART-BUILDAH docker image and push it to the registry
    export: true
    run:
      - $(build-image)
      - $(push-image)
...