---
name: pilotctl-app-dbman
description: database manager process for piloctl-app
port: "8086"
var:
  - name: OX_DBM_DB_HOST
    description: the database host to which dbman should connect
    value: "{{bind=db}}"
  - name: OX_DBM_DB_USERNAME
    description: the database user name
    value: "onix"
  - name: OX_DBM_DB_PASSWORD
    description: the database user password
    value: "{{fx=pwd:16,false}}"
    secret: true
  - name: OX_DBM_DB_ADMINUSERNAME
    description: the database server administrator user name
    value: "postgres"
  - name: OX_DBM_DB_ADMINPASSWORD
    description: the database server administrator password
    value: "{{bind=db:var:POSTGRES_PASSWORD}}"
    secret: true
  - name: OX_DBM_HTTP_USERNAME
    description: the user name for the http api
    value: "{{fx=name:99}}"
  - name: OX_DBM_HTTP_PASSWORD
    description: the password for the http api
    value: "{{fx=pwd:16,false}}"
    secret: true
  - name: OX_DBM_HTTP_AUTHMODE
    description: the http api authentication mode
    value: "basic"
  - name: OX_DBM_APPVERSION
    description: the version of the application for which database schemas will be deployed
    value: "0.0.4"
  - name: OX_DBM_REPO_URI
    description: the location of the database schemas
    value: "{{bind=pilotctl-app:schema_uri}}"
...