release = 1

[[schema]]
  file = "tables.ql"
  checksum = 0

[[function]]
  file = "validation.sql"
  checksum = 0

[[function]]
  file = "set.sql"
  checksum = 0

[[function]]
  file = "get.sql"
  checksum = 0

[[function]]
  file = "delete.sql"
  checksum = 0

[[function]]
  file = "queries.sql"
  checksum = 0

[[function]]
  file = "tree.sql"
  checksum = 0

[[function]]
  file = "tags.sql"
  checksum = 0
