# Artie's Build File
# It contains the instructions to build artie using itself
# No need for make, can run on windows, linux or mac providing the commands in the profiles or functions are compatible
---
type: native
license: Apache Version 2
labels:
  author: gatblau
  application: artie
  description: build, package, sign and publish application artefacts in a generic format as if they were docker images.
  architecture: amd64
env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: quay.io/gatblau
  ARTIE_REGISTRY: artie-registry
  ARTIE_IMG_BUILDER: artie-img-builder
  ARTIE_JAVA_BUILDER: artie-java-builder
  APP_VERSION: 0.0.4
profiles:
  - name: linux
    default: true
    labels:
      platform: linux
    env:
      GOOS: linux
    run:
      - $(build-linux)
    target: output/artie-linux-${APP_VERSION}-${ART_REF}
  - name: darwin
    labels:
      platform: darwin
    env:
      GOOS: darwin
    run:
      - go fmt
      - go build -o artie -v
    target: artie
functions:
  - name: build-linux
    description: builds the artie binary file for the linux platform
    env:
      GOOS: linux
    run:
      - rm -rf ./images/bin/output
      - sh ./images/bin/version.sh ${APP_VERSION}-${ART_REF}
      - go fmt
      - go build -o images/bin/output/artie-linux-${APP_VERSION}-${ART_REF} -v

  - name: build-registry-image
    description: creates an artie registry service image
    run:
      - $(build-linux)
      - docker pull registry.access.redhat.com/ubi8/ubi-minimal
      - docker build -f ./images/registry-svc/Dockerfile --build-arg APP_NAME=artie-linux-${APP_VERSION}-${ART_REF} -t ${REPO_NAME}/${ARTIE_REGISTRY}-snapshot:${APP_VERSION}-${ART_REF} .
      - docker tag ${REPO_NAME}/${ARTIE_REGISTRY}-snapshot:${APP_VERSION}-${ART_REF} ${REPO_NAME}/${ARTIE_REGISTRY}-snapshot:latest

  - name: push-registry-image
    description: creates a container image for the snapshot repository
    run:
      - docker push ${REPO_NAME}/${ARTIE_REGISTRY}-snapshot:$((cat ./version))
      - docker push ${REPO_NAME}/${ARTIE_REGISTRY}-snapshot:latest

  - name: build-img-builder-image
    description: creates an artie image builder image
    run:
      - $(build-linux)
      - docker pull docker.io/centos:7
      - docker build -f ./images/img-builder/Dockerfile --build-arg APP_NAME=artie-linux-${APP_VERSION}-${ART_REF} -t ${REPO_NAME}/${ARTIE_IMG_BUILDER}-snapshot:${APP_VERSION}-${ART_REF} .
      - docker tag ${REPO_NAME}/${ARTIE_IMG_BUILDER}-snapshot:${APP_VERSION}-${ART_REF} ${REPO_NAME}/${ARTIE_IMG_BUILDER}-snapshot:latest

  - name: push-img-builder-image
    description: pushes the image builder to the container registry
    run:
      - docker push ${REPO_NAME}/${ARTIE_IMG_BUILDER}-snapshot:$((cat ./version))
      - docker push ${REPO_NAME}/${ARTIE_IMG_BUILDER}-snapshot:latest

  - name: build-java-builder-image
    description: creates an artie java builder image
    run:
      - $(build-linux)
      - docker pull docker.io/centos:7
      - docker build -f ./images/java-builder/Dockerfile --build-arg APP_NAME=artie-linux-${APP_VERSION}-${ART_REF} -t ${REPO_NAME}/${ARTIE_JAVA_BUILDER}-snapshot:${APP_VERSION}-${ART_REF} .
      - docker tag ${REPO_NAME}/${ARTIE_JAVA_BUILDER}-snapshot:${APP_VERSION}-${ART_REF} ${REPO_NAME}/${ARTIE_JAVA_BUILDER}-snapshot:latest

  - name: push-java-builder-image
    description: pushes the java builder to the container registry
    run:
      - docker push ${REPO_NAME}/${ARTIE_JAVA_BUILDER}-snapshot:$((cat ./version))
      - docker push ${REPO_NAME}/${ARTIE_JAVA_BUILDER}-snapshot:latest

  - name: swagen
    description: generates/refreshes the OpenAPI specifications for Artie's HTTP API
    run:
      - swag init -d ./server -g server.go
...