- hosts: localhost
  tasks:
    - name: configure access to Onix
      ox_setup:
        uri: "{{ wapi_uri }}" # the URL where the Onix WAPI is listening
        username: "{{ user }}" # the username
        password: "{{ pwd }}" # the password
        auth_mode: "basic"
        # un-comment below to configure OpenId authentication / OAuth 2.0 authorisation
#        auth_mode: "oidc"
#        token_uri: "https://the-token-url-at-the-authorisation-server"
#        client_id: "the-client-id"
#        secret: "the-authorisation-server-secret"

    - name: create application meta model
      ox_model:
        uri: "{{ ox_uri }}"
        token: "{{ ox_token }}"
        key: "APPLICATION_MODEL"
        name: "Application Meta Model"
        description: "A meta model for describing software applications."

    - include: add_item_types.yml
    - include: add_link_types.yml
    - include: add_link_rules.yml
    - include: add_hosts.yml
    - include: add_runtimes.yml
    - include: add_app.yml
    - include: add_links.yml