# the oxterra service instance Id for logging identification purposes
Id = "Terra"

# verbosity of logging (Trace, Debug, Warning, Info, Error, Fatal, Panic)
LogLevel = "Trace"

# enables metrics
Metrics = "true"

# configuration for Terra Http Backend
AuthMode    = "basic"
Path        = "state"
Port        = "8081"
Username    = "admin"
Password    = "0n1x"

# configuration for the Onix Web API integration
[Onix]
    URL         = "http://localhost:8080"
    AuthMode    = "basic"
    Username    = "admin"
    Password    = "0n1x"
    ClientId    = ""
	AppSecret   = ""
	TokenURI    = ""
	InsecureSkipVerify = true