---
labels:
  author: onix@gatblau.org
  application: Onix Warden Proxy
  description: A traffic proxy providing traffic control and store and forward.
  architecture: amd64

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: quay.io/gatblau
  APP_VERSION: 0.0.4
  LIFECYCLE_STAGE: alpha
  ART_RUNNER: warden

functions:
  - name: set-version
    description: set-version on the parent build, updating global version
    run:
      - art run set-version ../
...
