---
labels:
  author: onix@gatblau.org
  application: Onix Pilot Host Control Service
  description: An HTTP API for managing Host Pilot agents

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: quay.io/gatblau
  APP_VERSION: 0.0.4
  APP_NAME: pilotctl

functions:
  - name: set-version
    description: updates the app version go file
    run:
      - sh version.sh ${APP_VERSION}-${ARTISAN_REF}

  - name: build-linux
    description: builds the PilotCtl binary file for the linux platform
    env:
      GOOS: linux
    run:
      - $(set-version)
      - go fmt
      - go build -o bin/pilotctl -v

  - name: swagen
    description: generates/refreshes the OpenAPI specifications for PilotCtl's HTTP API
    run:
      - swag init -d ./ -g handlers.go  --parseDependency core/types.go

  - name: build
    description: creates a Remote Host Service image
    run:
      - $(build-linux)
      - docker build -t ${REPO_NAME}/${APP_NAME}:$((cat ./version)) .
      - docker tag ${REPO_NAME}/${APP_NAME}:$((cat ./version)) ${REPO_NAME}/${APP_NAME}:latest

  - name: publish
    description: publishes the Remote Host Service image
    run:
      - docker push ${REPO_NAME}/${APP_NAME}:$((cat ./version))
      - docker push ${REPO_NAME}/${APP_NAME}:latest

  - name: release
    description: builds and publishes the Remote Host Service image
    run:
      - $(build)
      - $(publish)

  - name: up
    run:
      - docker run --name rem -d -p 8080:8080 ${REPO_NAME}/${APP_NAME}
...