---
- name: Creates a link between Spring Boot and Host A
  ox_link:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "RUNTIME-SPRING-BOOT-HOSTA"
    description: "Spring Boot is deployed on Host A."
    type: "APPLICATION"
    start_item_key: "RUNTIME-SPRING-BOOT"
    end_item_key: "HOST-A"
    tag:
    - "runtime"
    meta: {
      runtime: "Spring Boot",
      version: "1.5.10.RELEASE",
    }
    state: present

- name: Creates a link between Spring Boot and Host B
  ox_link:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "RUNTIME-SPRING-BOOT-HOSTB"
    description: "Spring Boot is deployed on Host B."
    type: "APPLICATION"
    start_item_key: "RUNTIME-SPRING-BOOT"
    end_item_key: "HOST-B"
    tag:
    - "runtime"
    meta: {
      runtime: "Spring Boot",
      version: "1.5.10.RELEASE",
    }

- name: Creates a link between Spring Boot and Host C
  ox_link:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "RUNTIME-SPRING-BOOT-HOSTC"
    description: "Spring Boot is deployed on Host C."
    type: "APPLICATION"
    start_item_key: "RUNTIME-SPRING-BOOT"
    end_item_key: "HOST-C"
    tag:
    - "runtime"
    meta: {
      runtime: "Spring Boot",
      version: "1.5.10.RELEASE",
    }

- name: Creates a link between PostgreSQL and Host D
  ox_link:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "DB-POSTGRESQL-HOSTD"
    description: "PostgreSQL is deployed on Host D."
    type: "APPLICATION"
    start_item_key: "DB-POSTGRESQL"
    end_item_key: "HOST-D"
    tag:
    - "rdbms"
    meta: {
      databaseType: "PostgreSQL",
      databaseVersion: "10.3",
    }

- name: Creates a link between PostgreSQL and Host E
  ox_link:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "DB-POSTGRESQL-HOSTE"
    description: "PostgreSQL is deployed on Host E."
    type: "APPLICATION"
    start_item_key: "DB-POSTGRESQL"
    end_item_key: "HOST-E"
    tag:
    - "rdbms"
    meta: {
      databaseType: "PostgreSQL",
      databaseVersion: "10.3",
    }

- name: Creates a link between Onix Web Service and Spring Boot
  ox_link:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "WEB-SERVICE-ONIX-WAPI-RUNTIME-SPRING-BOOT"
    description: "PostgreSQL is deployed on Host E."
    type: "APPLICATION"
    start_item_key: "WEB-SERVICE-ONIX-WAPI"
    end_item_key: "RUNTIME-SPRING-BOOT"
    tag:
    - "wapi"
    - "springboot"
    meta: {
    }

- name: Creates a link between Onix Data Service and PostgreSQL
  ox_link:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "DATA-SERVICE-ONIX-DB-DB-POSTGRESQL"
    description: "PostgreSQL is deployed on Host E."
    type: "APPLICATION"
    start_item_key: "DATA-SERVICE-ONIX-DB"
    end_item_key: "DB-POSTGRESQL"
    tag:
    - "db"
    - "postgresql"
    meta: {
    }

- name: Creates a link between Onix Application and Onix Application Data Service
  ox_link:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "APP-ONIX-CMDB-DATA-SERVICE-ONIX-DB"
    description: "The Onix application has a data service."
    type: "APPLICATION"
    start_item_key: "APP-ONIX-CMDB"
    end_item_key: "DATA-SERVICE-ONIX-DB"
    tag:
    - "onix"
    - "services"
    meta: {
    }

- name: Creates a link between Onix Application and Onix Application Web Service
  ox_link:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "APP-ONIX-CMDB-WEB-SERVICE-ONIX-WAPI"
    description: "The Onix application has a web service."
    type: "APPLICATION"
    start_item_key: "APP-ONIX-CMDB"
    end_item_key: "WEB-SERVICE-ONIX-WAPI"
    tag:
    - "onix"
    - "services"
    meta: {
    }