---
- name: Creates a configuration for Onix application WAPI Service
  ox_item:
    uri: "{{ ox_uri }}" # from fact
    token: "{{ ox_token }}" # from fact
    key: "WEB-SERVICE-ONIX-WAPI"
    name: "ONIX Web Service API"
    description: "Onix Web Service API"
    type: "WEB-SERVICE"
    meta: {}
    status: 1
    tag:
    - "onix"
    - "wapi"
    attribute:
      WBS: "EU-00023.100002.984"
      PROJECT: "TheOnixProject"

- name: Creates a configuration for Onix application Data Service
  ox_item:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "DATA-SERVICE-ONIX-DB"
    name: "ONIX Data Service"
    description: "Onix Data Service"
    type: "DATA-SERVICE"
    meta: {}
    status: 1
    tag:
    - "onix"
    - "db"
    attribute:
      WBS: "EU-00023.100002.984"
      PROJECT: "TheOnixProject"

- name: Creates a configuration for Onix CMDB application
  ox_item:
    uri: "{{ ox_uri }}"
    token: "{{ ox_token }}"
    key: "APP-ONIX-CMDB"
    name: "ONIX CMDB Application"
    description: "Ansible friendly configuration management database."
    type: "APPLICATION"
    meta: {}
    status: 1
    tag:
    - "onix"
    - "cmdb"
    attribute:
      WBS: "EU-00023.100002.984"
      PROJECT: "TheOnixProject"
...