- hosts: localhost
  tasks:
    - name: getting Onix access token
      onix_login:
        auth_host: "{{ auth_host }}"
        realm: "onix"
        client_id: "onix-cmdb"
        username: "onix"
        password: "onix"

    - include: add_item_types.yml
    - include: add_hosts.yml
    - include: add_runtimes.yml
    - include: add_app.yml
    - include: add_links.yml