info:
  contact:
    email: onix@gatblau.org
    name: gatblau
    url: http://onix.gatblau.org/
  description: Remote Ctrl Service for Onix Pilot
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Onix Remote
  version: 0.0.4
paths:
  /beat:
    post:
      description: receives a heart bit from a host agent via HTTP
      parameters:
      - description: the unique key identifying the host sending the heart beat
        in: body
        name: host-key
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: heart bit
      tags:
      - Agent
swagger: "2.0"
