info:
  contact:
    email: onix@gatblau.org
    name: gatblau
    url: http://onix.gatblau.org/
  description: Remote Ctrl Service for Onix Pilot
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Onix Remote Host
  version: 0.0.4
paths:
  /host:
    get:
      description: Returns a list of managed hosts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Host Query
      tags:
      - Admin
  /ping/{host-key}:
    post:
      description: receives a periodic ping request from Onix Pilot
      parameters:
      - description: the unique key for the host
        in: path
        name: host-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Host Ping
      tags:
      - Pilot
swagger: "2.0"
