---
labels:
  author: onix@gatblau.org
  application: Kubernetes Cluster Ops Manager
  description: Deploy and manage Kubernetes clusters using an HTTP api

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  APP_NAME: k
  APP_VERSION: 0.0.4
  BUILD_VERSION: ${APP_VERSION}-${ARTISAN_REF}
functions:
  - name: build-linux
    env:
      GOOS: linux
    run:
      - $(build)

  - name: build-mac
    env:
      GOOS: darwin
    run:
      - $(build)

  - name: build
    description: generic platform agnostic build for the service
    run:
      - go fmt
      - go build -ldflags="-X 'github.com/gatblau/onix/k/core.Version=${BUILD_VERSION}'" -o bin/${GOOS}/k -v

  - name: swagen
    description: generates/refreshes the OpenAPI specifications for K's HTTP API
    run:
      - swag init -d ./ -g handlers.go  --parseDependency types/*.go

...