---
labels:
  author: onix@gatblau.org
  application: Onix Artisan Flow Runner
  description: An HTTP API for executing Artisan flows.
  architecture: amd64

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: quay.io/gatblau
  ART_RUNNER: artisan-runner
  APP_VERSION: 0.0.4
  BUILD_VERSION: ${APP_VERSION}-${ARTISAN_REF}

profiles:

functions:
  - name: build-linux
    description: builds the Artisan Flow Runner for the linux platform
    env:
      GOOS: linux
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/runner/tkn/core.Version=${BUILD_VERSION}'"  -o bin/linux/runner -v

  - name: build-mac
    description: builds the Artisan Flow Runner for the MacOS platform
    env:
      GOOS: darwin
    run:
      - go build -ldflags="-X 'github.com/gatblau/onix/artisan/runner/tkn/core.Version=${BUILD_VERSION}'"  -o bin/linux/runner -v

  - name: release
    description: creates an Artisan Flow Runner image
    run:
      - $(build-linux)
      - docker build -t ${REPO_NAME}/${ART_RUNNER}:${BUILD_VERSION} .
      - docker tag ${REPO_NAME}/${ART_RUNNER}:${BUILD_VERSION} ${REPO_NAME}/${ART_RUNNER}:latest
      - docker push ${REPO_NAME}/${ART_RUNNER}:${BUILD_VERSION}
      - docker push ${REPO_NAME}/${ART_RUNNER}:latest

  - name: swagen
    description: generates/refreshes the OpenAPI specifications for Artisan's HTTP API
    run:
      - swag init -d ./ -g handlers.go --parseDependency ../flow/flow.go
...