basePath: /
host: localhost
info:
  contact:
    email: onix@gatblau.org
    name: gatblau
  description: |-
    This service makes some of DbMan's cli commands available via HTTP.
    Its main purpose is to facilitate key database maintenance operations in containerised environments.

    NOTE: Any commands which are meant to modify configuration sets are not available from this service because it is
    assumed to run from a container. Therefore, service configuration can only be set via environment variables.
  license:
    name: Apache License, Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  title: Onix Database Manager Web API.
  version: 0.0.4
paths:
  /conf:
    get:
      description: List all configuration variables.
      operationId: SHOW
      responses:
        "200":
          $ref: '#/responses/confResponse'
      summary: SHOW
      tags:
      - CONFIGURATION
  /conf/check:
    get:
      description: |-
        Checks that a connection can be established to the database and remote git repository based on the specified configuration.

        Configuration is provided as environment variables to the running service.
      operationId: CHECK
      responses:
        "200":
          $ref: '#/responses/confCheckResponse'
      summary: CHECK
      tags:
      - CONFIGURATION
  /db/run/{taskName}/{appVersion}:
    post:
      description: |-
        Executes the database task defined in a remote git repository.

        Configuration is provided as environment variables to the running service.
      operationId: RUN
      parameters:
      - description: The application version to deploy
        in: path
        name: taskName
        required: true
        type: string
        x-go-name: TaskName
      responses:
        "200":
          $ref: '#/responses/dbRunResponse'
      summary: RUN
      tags:
      - DATABASE
produces:
- text/plain
responses:
  confCheckResponse:
    description: A list of checks and their result displayed in text form.
  confResponse:
    description: The list of configuration variables used by DbMan.
  dbRunResponse:
    description: The output of the run command execution as a plain text log.
schemes:
- http
- https
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
