basePath: /
host: localhost
info:
  contact:
    email: onix@gatblau.org
    name: gatblau
  description: |-
    This service makes some of DbMan's cli commands available via HTTP.
    Its main purpose is to facilitate key database maintenance operations in containerised environments.

    NOTE: Any commands which are meant to modify configuration sets are not available from this service because it is
    assumed to run from a container. Therefore, service configuration can only be set via environment variables.
  license:
    name: Apache License, Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  title: Onix Database Manager Web API.
  version: 0.0.4
paths:
  /conf:
    get:
      description: List all configuration variables.
      operationId: SHOW
      responses:
        "200":
          $ref: '#/responses/confResponse'
      summary: SHOW
      tags:
      - CONFIGURATION
  /conf/check:
    get:
      description: |-
        Checks that a connection can be established to the database and remote git repository based on the specified configuration.

        Configuration is provided as environment variables to the running service.
      operationId: CHECK
      responses:
        "200":
          $ref: '#/responses/confCheckResponse'
      summary: CHECK
      tags:
      - CONFIGURATION
  /db/create:
    post:
      description: Creates a new database based on the release manifest.
      operationId: CREATE
      responses:
        "200":
          $ref: '#/responses/dbCreateResponse'
      summary: CREATE
      tags:
      - DATABASE
  /db/deploy:
    post:
      description: Deploys the database schemas and objects for the current database
        release.
      operationId: DEPLOY
      responses:
        "200":
          $ref: '#/responses/dbDeployResponse'
      summary: DEPLOY
      tags:
      - DATABASE
  /db/server:
    get:
      description: Gets database server information.
      operationId: SERVER
      responses:
        "200":
          $ref: '#/responses/dbServerResponse'
      summary: SERVER
      tags:
      - DATABASE
produces:
- text/plain
responses:
  confCheckResponse:
    description: A list of checks and their result displayed in text form.
  confResponse:
    description: The list of configuration variables used by DbMan.
  dbCreateResponse:
    description: The output of the create command execution.
  dbDeployResponse:
    description: The output of the deploy command execution.
  dbServerResponse:
    description: The output of the server command execution.
schemes:
- http
- https
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
