basePath: /
info:
  contact:
    email: onix@gatblau.org
    name: gatblau
  description: |-
    This service makes some of DbMan's cli commands available via HTTP.
    Its main purpose is to facilitate key database maintenance operations in containerised environments.

    NOTE: Any commands which are meant to modify configuration sets are not available from this service because it is
    assumed to run from a container. Therefore, service configuration can only be set via environment variables.
  license:
    name: Apache License, Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  title: Onix DbMan Web API.
  version: 0.0.4
paths:
  /conf:
    get:
      description: List all configuration variables used by DbMan.
      operationId: show
      responses:
        "200":
          $ref: '#/responses/cmdResponse'
      summary: Show Configuration
      tags:
        - Configuration
  /conf/check:
    get:
      summary: Validate Configuration
      description: Check that the configuration points to valid backend services and relevant connections can be established successfuly.
      operationId: check
      responses:
        "200":
          $ref: '#/responses/cmdResponse'
      tags:
        - Configuration
  /db/create:
    post:
      operationId: create
      responses:
        "200":
          $ref: '#/responses/cmdResponse'
      summary: Create Database
      description: Create the database as specified in the release manifest. If the database already exists, an error message is returned.
      tags:
        - Database
  /db/deploy:
    post:
      summary: Deploy Schema
      description: Deploys the database schema and objects as specified in the release manifest.
      operationId: deploy
      responses:
        "200":
          $ref: '#/responses/cmdResponse'
      tags:
        - Database
  /db/upgrade:
    post:
      summary: Upgrade Schema
      description: Upgrades the database schema and objects as specified in the release manifest.
      operationId: upgrade
      responses:
        "200":
          $ref: '#/responses/cmdResponse'
      tags:
        - Database
  /db/version:
    get:
      summary: Get Version
      description: Returns the current database release version information.
      operationId: version
      responses:
        "200":
          $ref: '#/responses/dbVersionResponse'
      tags:
        - Database
  /db/query/{name}:
    get:
      summary: Query Database
      description: |-
        Execute the query identified by the "name" path parameter.
        Query parameters can be passed in via the query string.
      operationId: query
      parameters:
        - name: name
          description: The name of the query (as defined in the manifest) to be executed.
          in: path
          required: true
          type: string
        - name: params
          description: The query parameters as a pipe "|" separated list of key=value pairs.
          in: query
          type: string
      responses:
        "200":
          $ref: '#/responses/dbQueryResponse'
      tags:
        - Database
  /db/server:
    get:
      summary: Get Server Info
      description: Gets information about the database server specified in the DbMan's configuration.
      operationId: server
      responses:
        "200":
          $ref: '#/responses/cmdResponse'
      tags:
        - Database
  /db/backup:
    post:
      summary: Backup Database
      description: Backups the database.
      operationId: backup
      responses:
        "200":
          $ref: '#/responses/cmdResponse'
      tags:
        - Database
  /db/restore:
    post:
      summary: Restore Database
      description: Restores the database.
      operationId: restore
      responses:
        "200":
          $ref: '#/responses/cmdResponse'
      tags:
        - Database
  /release/plan:
    get:
      summary: Get Release Plan
      description: Returns the release plan in the scripts repository.
      operationId: plan
      responses:
        "200":
          $ref: '#/responses/releasePlanResponse'
      tags:
        - Release
  /release/manifest:
    get:
      summary: Get Release Manifest
      description: Returns the release manifest for the application version specified in DbMan's configuration.
      operationId: manifest
      responses:
        "200":
          $ref: '#/responses/releaseManifestResponse'
      tags:
        - Release
produces:
  - text/plain
responses:
  dbVersionResponse:
    description: The application and database versions.
  dbQueryResponse:
    description: The result of the database query.
  cmdResponse:
    description: The execution logs in text format.
  releasePlanResponse:
    description: The release plan.
  releaseManifestResponse:
    description: The release manifest.
schemes:
  - http
  - https
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
