apiVersion: v1
kind: Template
metadata:
  name:  onix-persistent
  annotations:
    description: "Deploys Onix Config Manager with persistent storage."
parameters:
  - name: OX_DB_ADM_PWD
    displayName: Onix PostgreSQL Administrator Password
    description: The admin password for the PostgreSQL database used by Onix.
    required: true
    from: "[a-zA-Z0-9]{8}"
    generate: expression
  - name: OX_DB_PWD
    displayName: Onix Database User Password
    description: The Onix database user password.
    required: true
    from: "[a-zA-Z0-9]{8}"
    generate: expression
  - name: OX_WAPI_ADMIN_PWD
    displayName: Onix Web API Administrator Role Password
    description: The Onix Web API administrator role password.
    required: true
    from: "[a-zA-Z0-9]{8}"
    generate: expression
  - name: OX_WAPI_WRITER_PWD
    displayName: Onix Web API Writer Role Password
    description: The Onix Web API writer role password.
    required: true
    from: "[a-zA-Z0-9]{8}"
    generate: expression
  - name: OX_WAPI_READER_PWD
    displayName: Onix Web API Reader Role Password
    description: The Onix Web API reader role password.
    required: true
    from: "[a-zA-Z0-9]{8}"
    generate: expression
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: onixdb
  spec:
    replicas: 1
    progressDeadlineSeconds: 600
    revisionHistoryLimit: 10
    selector:
        deploymentconfig: onixdb
    strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
    template:
      metadata:
        labels:
          app: onix
          deploymentconfig: onixdb
      spec:
        containers:
        - name: onixdb
          env:
          - name: POSTGRESQL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: onix-db-admin
                key: pwd
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: onixdb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: onixdb-data
          persistentVolumeClaim:
            claimName: onixdb
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - onixdb
        from:
           kind: ImageStreamTag
           name: onixdb:latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: onix
    name: onixdb
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations:
      from:
        kind: DockerImage
        name: centos/postgresql-10-centos7
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Local
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: onixwapi
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
        deploymentconfig: onixwapi
    strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
    template:
      metadata:
        labels:
          app: onix
          deploymentconfig: onixwapi
      spec:
        containers:
        - env:
          - name: DB_HOST
            value: onixdb
          - name: WAPI_AUTH_MODE
            value: basic
          - name: DB_ADMIN_PWD
            valueFrom:
              secretKeyRef:
                key: pwd
                name: onix-db-admin
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: onix-db-user
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                key: pwd
                name: onix-db-user
          - name: WAPI_ADMIN_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: onix-wapi-admin-user
          - name: WAPI_ADMIN_PWD
            valueFrom:
              secretKeyRef:
                key: pwd
                name: onix-wapi-admin-user
          - name: WAPI_READER_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: onix-wapi-reader-user
          - name: WAPI_READER_PWD
            valueFrom:
              secretKeyRef:
                key: pwd
                name: onix-wapi-reader-user
          - name: WAPI_WRITER_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: onix-wapi-writer-user
          - name: WAPI_WRITER_PWD
            valueFrom:
              secretKeyRef:
                key: pwd
                name: onix-wapi-writer-user
          - name: MGMT_ENDPOINT_METRICS_ENABLED
            value: "true"
          - name: DS_PREP_STMT_CACHE_SIZE
            value: "250"
          - name: DS_PREP_STMT_CACHE_SQL_LIMIT
            value: "2048"
          - name: DS_CACHE_PREP_STMTS
            value: "true"
          - name: DS_USE_SERVER_PREP_STMTS
            value: "true"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: onixwapi
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - onixwapi
        from:
           kind: ImageStreamTag
           name: onixwapi:latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: onix
    name: onixwapi
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations:
      from:
        kind: DockerImage
        name: gatblau/onix
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Local
- apiVersion: v1
  kind: Secret
  metadata:
    name: onix-db-user
  type: Opaque
  data:
    user: b25peA==
  stringData:
    pwd: "${OX_DB_PWD}"
- apiVersion: v1
  kind: Secret
  metadata:
    name: onix-db-admin
  type: Opaque
  stringData:
    pwd: "${OX_DB_ADM_PWD}"
- apiVersion: v1
  kind: Secret
  metadata:
    name: onix-wapi-admin-user
  type: Opaque
  data:
    user: YWRtaW4=
  stringData:
    pwd: "${OX_WAPI_ADMIN_PWD}"
- apiVersion: v1
  kind: Secret
  metadata:
    name: onix-wapi-reader-user
  type: Opaque
  data:
    user: cmVhZGVy
  stringData:
    pwd: "${OX_WAPI_READER_PWD}"
- apiVersion: v1
  kind: Secret
  metadata:
    name: onix-wapi-writer-user
  type: Opaque
  data:
    user: d3JpdGVy
  stringData:
    pwd: "${OX_WAPI_WRITER_PWD}"
- apiVersion: v1
  kind: Service
  metadata:
    name: onixdb
  spec:
    ports:
    - name: "5432"
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      deploymentconfig: onixdb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: onixwapi
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: onixwapi
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: onixwapi
  spec:
    port:
      targetPort: 8080
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: onixwapi
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: onixdb
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
