AppVersion = "0.0.4"
Theme = ""
[Http]
	Metrics  = "true"
	AuthMode = "basic"
	Port     = "8085"
	Username = "admin"
	Password = "0n1x"
[Db]
    Provider      = "_pgsql"
    Name          = "onix"
    Host          = "localhost"
    Port          = "5432"
    Username      = "onix"
    Password      = "onix"
    AdminUsername = "postgres"
    AdminPassword = "onix"
[Repo]
    URI      = "https://raw.githubusercontent.com/gatblau/ox-db/master"
    Username = ""
    Password = ""
