# the dbman service instance Id for logging identification purposes
Id = "DbMan"

# verbosity of logging (Trace, Debug, Warning, Info, Error, Fatal, Panic)
LogLevel = "Trace"

# enables metrics
Metrics = "true"

# configuration for DbMan
AuthMode    = "basic"
Port        = "8085"
Username    = "admin"
Password    = "0n1x"

# configuration for the Onix Web API integration
[Db]
    Name        = "onix"
    ConnString  = "http://localhost:8080"
    Username    = "admin"
    Password    = "0n1x"
[Schema]
    Path        = "~/dev/onix/wapi/src/main/resources/db/install"